/**
 * Style Dictionary (v4) build for the Chimi design system.
 *
 * Inputs:  design-system/tokens/{color,font,size,type-style,breakpoint}.*.json
 * Outputs: design-system/dist/tokens.css        (CSS custom properties + type-style shorthands)
 *          design-system/dist/breakpoints.css   (short --bp-* vars + @custom-media queries
 *                                                 for mobile-first authoring in webs)
 *
 * Run:     npm run tokens:build
 *
 * Naming convention in CSS: `--chimi-{path-joined-by-dashes}` — paths are
 * taken from the JSON structure (e.g. color.surface.canvas → --chimi-color-surface-canvas).
 * Breakpoints additionally get a short alias (--bp-sm/md/lg/xl) plus
 * @custom-media queries (--sm, --md, --lg, --xl) emitted in breakpoints.css
 * for ergonomic consumption (see responsive-foundation spec).
 *
 * Type-style composites (objects under `type.*` that group fontFamily/fontSize/…
 * together) get BOTH per-property variables AND a single `font:` shorthand,
 * so a layout can write `font: var(--chimi-type-display-md)` in one line.
 *
 * Theming: a token can declare per-theme overrides via
 *   "$extensions": { "chimi.theme": { "light": "{primitives.color.ivory.base}" } }
 * The default ($value) goes in :root; each named theme emits a
 * :root[data-theme="<theme>"] block with only the overridden roles.
 */

import StyleDictionary from "style-dictionary";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const TYPE_ROOT = "type";
const THEME_EXT_KEY = "chimi.theme";
const RECIPE_ROLES = ["surface", "ink", "em", "accent", "warn", "font-primary", "weight-primary", "letter-spacing-primary", "opacity-primary", "font-secondary", "weight-secondary", "letter-spacing-secondary", "opacity-secondary", "font-display", "weight-display", "font-body", "weight-body", "font-editorial", "weight-editorial", "font-data", "weight-data", "font-code", "weight-code"];

const RECIPE_SOURCE = resolve(HERE, "tokens/color.recipe.json");

/**
 * Sources scanned for $extensions["chimi.theme"] overrides.
 *
 * Pre-2026-05 this list was named `SEMANTIC_SOURCES` and contained only
 * `color.semantic.json` (deleted by the `recipes-light-theme-support`
 * change). Recipes now own per-theme overrides via the same
 * `$extensions.chimi.theme.<name>` mechanism — the walker is generic, so
 * any new theme-aware token file just needs to be appended here.
 */
const THEME_SOURCES = [
  RECIPE_SOURCE,
];

const sd = new StyleDictionary({
  usesDtcg: true,
  source: [
    resolve(HERE, "tokens/color.primitive.json"),
    resolve(HERE, "tokens/color.recipe.json"),
    resolve(HERE, "tokens/font.primitive.json"),
    resolve(HERE, "tokens/font.semantic.json"),
    resolve(HERE, "tokens/size.primitive.json"),
    resolve(HERE, "tokens/type-style.semantic.json"),
    resolve(HERE, "tokens/breakpoint.primitive.json"),
  ],
  platforms: {
    css: {
      transformGroup: "css",
      buildPath: resolve(HERE, "dist") + "/",
      files: [
        {
          destination: "tokens.css",
          format: "chimi/css-variables",
        },
        {
          destination: "breakpoints.css",
          format: "chimi/breakpoints-css",
        },
      ],
    },
  },
});

// Theme overrides are read directly from theme-source JSON before SD runs.
// Style Dictionary v4 doesn't expose $extensions on resolved tokens reliably,
// so we parse the raw files ourselves and resolve {primitives.…} references
// against the same primitives SD sees. Today only color.recipe.json carries
// theme overrides (post-`recipes-light-theme-support` migration); the walker
// is generic so new theme-aware files can be added to THEME_SOURCES.
const themeOverridesByPath = await collectThemeOverrides();
const criticalFgModifiers = await loadCriticalFgModifiers();

sd.registerFormat({
  name: "chimi/css-variables",
  format: async ({ dictionary }) => {
    const out = [];
    out.push("/* Generated by design-system/config.js — do not edit by hand. */");
    out.push("/* Source: design-system/tokens/*.json                         */");
    out.push(":root {");

    // 1. Leaf tokens → --chimi-<path>
    for (const token of dictionary.allTokens) {
      out.push(`  --chimi-${token.path.join("-")}: ${token.$value};`);
    }

    // 2. Type-style shorthands: walk the raw token tree under `type.*`
    //    and emit a single `font:` shorthand variable per style.
    out.push("");
    out.push("  /* Type-style shorthands — use as `font: var(--chimi-type-…)`. */");
    const typeRoot = dictionary.tokens[TYPE_ROOT] || {};
    walkTypeStyles(typeRoot, [TYPE_ROOT], (path, style) => {
      const shorthand = buildFontShorthand(style);
      if (shorthand) out.push(`  --chimi-${path.join("-")}: ${shorthand};`);
    });

    out.push("}");

    // 3. Per-theme override blocks: one :root[data-theme="<theme>"] block per
    //    theme name found in $extensions["chimi.theme"]. Only roles whose
    //    value differs from the default are emitted.
    const themes = groupOverridesByTheme(themeOverridesByPath, dictionary);
    for (const [themeName, entries] of themes) {
      if (entries.length === 0) continue;
      out.push("");
      out.push(`:root[data-theme="${themeName}"] {`);
      for (const { cssVar, value } of entries) {
        out.push(`  ${cssVar}: ${value};`);
      }
      out.push("}");
    }

    // 4. Per-recipe selector blocks: one :where([data-recipe="<id>"]) per
    //    recipe under color.recipe.*. Each block populates the 5 short vars
    //    --recipe-{surface,ink,em,accent,warn} from the long --chimi-color-recipe-*
    //    tokens emitted in step 1. Layouts only consume --recipe-*.
    const recipes = collectRecipeIds(dictionary);
    if (recipes.length) {
      out.push("");
      out.push("/* Recipe selectors — populate --recipe-* short vars from --chimi-color-recipe-*. */");
      for (const id of recipes) {
        out.push(`:where([data-recipe="${id}"]) {`);
        for (const role of RECIPE_ROLES) {
          out.push(`  --recipe-${role}: var(--chimi-color-recipe-${id}-${role});`);
        }
        out.push("}");
      }

      // 5. Critical-fg classes: read from color.recipe.json::critical._fgModifiers.
      //    Each modifier overrides one --recipe-* var with the surface color
      //    of the critical recipe (plasma). Single source of truth lives in
      //    the JSON; if a new role appears there, it's emitted automatically.
      if (Object.keys(criticalFgModifiers).length) {
        out.push("");
        out.push("/* Critical-fg modifiers — generated from color.recipe.json::critical._fgModifiers. */");
        out.push("/* Apply alongside data-recipe to override one role with plasma. */");
        for (const [role, mod] of Object.entries(criticalFgModifiers)) {
          const target = `--recipe-${mod.overrides}`;
          const value = resolveRef(mod.color, dictionary) ?? mod.color;
          out.push(`.critical-fg-${role} { ${target}: ${value}; }`);
        }
      }
    }

    return out.join("\n") + "\n";
  },
});

sd.registerFormat({
  name: "chimi/breakpoints-css",
  format: ({ dictionary }) => {
    // Webs consume the short `--bp-*` aliases and write `@media (--md) { … }`
    // for mobile-first authoring. The long `--chimi-primitives-bp-*` vars
    // already ship in tokens.css; this file is the ergonomic public surface.
    //
    // postcss-custom-media (part of the Astro/Vite pipeline via lightningcss
    // and postcss-preset-env defaults) inlines `@media (--md)` to literal
    // `@media (min-width: 768px)` at build time. Browsers without native
    // @custom-media support still get a working bundle.
    const bpRoot = dictionary.tokens?.primitives?.bp;
    if (!bpRoot || typeof bpRoot !== "object") {
      return "/* No bp.* primitives found — nothing to emit. */\n";
    }
    const ids = Object.keys(bpRoot).filter((k) => !k.startsWith("$") && !k.startsWith("_"));
    const out = [];
    out.push("/* Generated by design-system/config.js — do not edit by hand. */");
    out.push("/* Source: design-system/tokens/breakpoint.primitive.json       */");
    out.push("/*                                                              */");
    out.push("/* Webs author mobile-first CSS using these:                    */");
    out.push("/*   .grid { display: grid; grid-template-columns: 1fr; }       */");
    out.push("/*   @media (--md) {                                            */");
    out.push("/*     .grid { grid-template-columns: repeat(3, 1fr); }         */");
    out.push("/*   }                                                          */");
    out.push(":root {");
    for (const id of ids) {
      const node = bpRoot[id];
      const value = node && typeof node === "object" && "$value" in node ? node.$value : null;
      if (!value) continue;
      out.push(`  --bp-${id}: ${value};`);
    }
    out.push("}");
    out.push("");
    out.push("/* @custom-media queries — write `@media (--md) { … }` in webs. */");
    for (const id of ids) {
      const node = bpRoot[id];
      const value = node && typeof node === "object" && "$value" in node ? node.$value : null;
      if (!value) continue;
      out.push(`@custom-media --${id} (min-width: ${value});`);
    }
    return out.join("\n") + "\n";
  },
});

/** Read each theme-source JSON and collect every leaf with a
 *  $extensions["chimi.theme"] block. Returns Map<dottedPath, { defaultRef, themes: { [name]: ref } }>. */
async function collectThemeOverrides() {
  const overrides = new Map();
  for (const file of THEME_SOURCES) {
    const json = JSON.parse(await readFile(file, "utf8"));
    walkRawTokens(json, [], (path, node) => {
      const ext = node.$extensions && node.$extensions[THEME_EXT_KEY];
      if (!ext || typeof ext !== "object") return;
      overrides.set(path.join("."), {
        defaultRef: node.$value,
        themes: { ...ext },
      });
    });
  }
  return overrides;
}

/** Walk a raw DTCG-shaped JSON tree, calling visit(path, leafNode) for any
 *  node that has a $value (i.e. is a token leaf). */
function walkRawTokens(node, path, visit) {
  if (!node || typeof node !== "object") return;
  if ("$value" in node) {
    visit(path, node);
    return;
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("$") || key.startsWith("_")) continue;
    walkRawTokens(child, [...path, key], visit);
  }
}

/** Resolve a Style Dictionary reference like "{primitives.color.ivory.base}"
 *  by looking up the resolved value in the built dictionary. Plain strings
 *  (e.g. raw hex) are returned as-is. */
function resolveRef(ref, dictionary) {
  if (typeof ref !== "string") return null;
  const m = ref.match(/^\{([^}]+)\}$/);
  if (!m) return ref;
  const segments = m[1].split(".");
  let cursor = dictionary.tokens;
  for (const seg of segments) {
    if (!cursor || typeof cursor !== "object") return null;
    cursor = cursor[seg];
  }
  if (cursor && typeof cursor === "object" && "$value" in cursor) return cursor.$value;
  return null;
}

/** Group override entries by theme name, mapping each to its CSS var name and
 *  resolved value. Skips entries whose resolved value matches the default
 *  (so identical declarations don't pollute the override block). */
function groupOverridesByTheme(overridesByPath, dictionary) {
  const byTheme = new Map();
  for (const [dotted, { defaultRef, themes }] of overridesByPath) {
    const path = dotted.split(".");
    const cssVar = `--chimi-${path.join("-")}`;
    const defaultValue = resolveRef(defaultRef, dictionary);
    for (const [themeName, ref] of Object.entries(themes)) {
      const value = resolveRef(ref, dictionary);
      if (value == null) continue;
      if (value === defaultValue) continue;
      if (!byTheme.has(themeName)) byTheme.set(themeName, []);
      byTheme.get(themeName).push({ cssVar, value });
    }
  }
  return byTheme;
}

/** Read color.recipe.json::critical._fgModifiers — Style Dictionary doesn't
 *  expose this nested metadata reliably, so we parse the raw JSON ourselves
 *  and rely on resolveRef() at emit time to turn {primitives.…} into a hex. */
async function loadCriticalFgModifiers() {
  const json = JSON.parse(await readFile(RECIPE_SOURCE, "utf8"));
  const mods = json?.color?.recipe?.critical?._fgModifiers ?? {};
  const out = {};
  for (const [role, spec] of Object.entries(mods)) {
    if (role.startsWith("$") || role.startsWith("_")) continue;
    if (!spec || typeof spec !== "object") continue;
    out[role] = { overrides: spec.overrides, color: spec.color };
  }
  return out;
}

/**
 * A type-style node is an object that groups fontFamily + fontSize + siblings.
 * Style Dictionary stores leaves as { value, ... }, so we look for an object
 * whose `fontFamily` child itself has a `value` — that marks a composite.
 */
function walkTypeStyles(node, path, visit) {
  if (!node || typeof node !== "object") return;
  if (isTypeStyleNode(node)) {
    const resolved = {};
    for (const key of ["fontStyle", "fontWeight", "fontSize", "lineHeight", "fontFamily", "letterSpacing", "textTransform"]) {
      if (node[key] && node[key].$value !== undefined) resolved[key] = node[key].$value;
    }
    visit(path, resolved);
    return;
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("_") || key.startsWith("$")) continue;
    walkTypeStyles(child, [...path, key], visit);
  }
}

function isTypeStyleNode(node) {
  return (
    node.fontFamily &&
    typeof node.fontFamily === "object" &&
    "$value" in node.fontFamily &&
    node.fontSize &&
    typeof node.fontSize === "object" &&
    "$value" in node.fontSize
  );
}

/** Collect every recipe id under color.recipe.*. Returns an array of ids
 *  (e.g. ["canvas-quiet", "canvas-signal", …]) in declaration order. */
function collectRecipeIds(dictionary) {
  const recipeRoot = dictionary.tokens?.color?.recipe;
  if (!recipeRoot || typeof recipeRoot !== "object") return [];
  return Object.keys(recipeRoot).filter((key) => !key.startsWith("$") && !key.startsWith("_"));
}

/** Build a CSS `font:` shorthand. letter-spacing/text-transform aren't part of
 *  the shorthand so we only encode style/weight/size[/line-height]/family. */
function buildFontShorthand(style) {
  if (!style.fontFamily || !style.fontSize) return null;
  const parts = [];
  if (style.fontStyle) parts.push(style.fontStyle);
  if (style.fontWeight) parts.push(style.fontWeight);
  parts.push(style.lineHeight ? `${style.fontSize}/${style.lineHeight}` : style.fontSize);
  parts.push(style.fontFamily);
  return parts.join(" ");
}

await sd.hasInitialized;
await sd.buildAllPlatforms();
console.log("✓ design-system tokens built → design-system/dist/");
// Keep a reference so esbuild/linters don't complain about unused import.
void readFile;
